rango/urls.py
# coding:utf-8
from django.conf.urls import url
from django.views.generic import TemplateView

from rango import views
from rango.views import *


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^about/', TemplateView.as_view(template_name="rango/about.html"), name='about'),

    ## USER ##
    url(r'^add_user$', views.AddUser, name="add_user"),
    url(r'^register/$', views.Register, name='register'),
    url(r'^login/$', views.UserLogin, name='login'),
    url(r'^restricted/$', login_required(TemplateView.as_view(template_name="rango/restricted.html")), name='restricted'),
    url(r'^logout/$', views.UserLogout, name='logout'),

    ## CATEGORY ##
    url(r'^category/(?P<category_name_slug>[\w\-]+)/$', views.ShowCategory, name='category'),
    url(r'^category/$', views.GoToCategory, name='gotocategory'),
    url(r'^cad/category/$', CategoryView.as_view(), name='cad_category'),
    url(r'^edita/category/(?P<id>[0-9]+)/$', CategoryView.as_view(), name='edita_category'),
    url(r'^deleta/category/(?P<id>[0-9]+)/$', views.CategoryDelete, name='deleta_category'),
    url(r'^categories/', views.ListCategories, name='categories'),
    url(r'^likecategory/$', views.LikeCategory, name='likecategory'),

    ## PAGE ##
    url(r'^category/(?P<category_name_slug>[\w\-]+)/cad/page/$', PageView.as_view(), name='cad_page'),
    url(r'^edita/page/(?P<id>[0-9]+)/$', PageView.as_view(), name='edita_page'),
    url(r'^deleta/page/(?P<id>[0-9]+)/$', views.PageDelete, name='deleta_page'),
    url(r'^page/$', views.GoToPage, name='gotopage'),
    url(r'^pages/', views.Pages, name='pages'),
    url(r'^search$', views.Search, name='search'),

    ## DJANGO OFICIAL ##
    url(r'^question/(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^question/(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
    url(r'^question/(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
]

tango_with_django_project/urls.py
# coding: utf-8
from django.conf.urls import include, url
from django.contrib import admin
from rango import views


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^rango/', include('rango.urls', namespace="rango")),
    url(r'^$', views.index, name='index'),
]

rango/models/category.py
#coding: utf-8
from django.db import models
from django.template.defaultfilters import slugify


class CategoryModel(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField()

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(CategoryModel, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    def __unicode__(self):
        return self.name

rango/models/user_profile.py
#coding: utf-8
from django.db import models
from django.contrib.auth.models import User


class UserProfileModel(models.Model):
    user = models.OneToOneField(User)
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    def __unicode__(self):
        return self.user.username

rango/forms.py
#coding: utf-8
from django import forms
from django.contrib.auth.models import User
from rango.models import Page, Category, UserProfile
from django.core import validators


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('website', 'picture')

class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128, help_text="Please enter the category name.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    # An inline class to provide additional information on the form.
    class Meta:
        # Provide an association between the ModelForm and a model
        model = Category
        fields = ('name',)


class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128, help_text="Please enter the title of the page.")
    url = forms.URLField(max_length=200, help_text="Please enter the URL of the page.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        # Provide an association between the ModelForm and a model
        model = Page

        # What fields do we want to include in our form?
        # This way we don't need every field in the model present.
        # Some fields may allow NULL values, so we may not want to include them...
        # Here, we are hiding the foreign key.
        # we can either exclude the category field from the form,
        exclude = ('category',)
        #or specify the fields to include (i.e. not include the category field)
        #fields = ('title', 'url', 'views')

    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')

        # If url is not empty and doesn't start with 'http://', prepend 'http://'.
        if url and not url.startswith('http://'):
            url = 'http://' + url
            cleaned_data['url'] = url

        return cleaned_data

rango/forms/category.py
#coding: utf-8
from django import forms
from rango.models import CategoryModel


class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128, help_text="Nome: ")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = CategoryModel
        fields = ('name',)

rango/forms/page.py
# coding: utf-8
from django import forms
from rango.models import PageModel


class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128, help_text="Título: ", required=True)
    url = forms.CharField(max_length=200, help_text="URL: ", required=True,
                          widget=forms.TextInput(attrs={'placeholder': 'http:// ...'}))
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        model = PageModel
        exclude = ('category',)

    # def clean_url(self):
    #     url = self.cleaned_data.get('url')
    #     if not url.startswith('http://') or not url.startswith('https://'):
    #         print("deu tiuti")
    #         raise forms.ValidationError("Informe uma URL válida.")
    #     else:
    #         return url

rango/forms/user.py
#coding: utf-8
from django import forms
from django.contrib.auth.models import User
from rango.models import UserProfileModel


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfileModel
        fields = ('website', 'picture')

rango/views/category.py
# coding: utf-8
from django.shortcuts import render, HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from rango.models import CategoryModel, PageModel
from rango.forms import CategoryForm
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic.base import View


class CategoryView(View):
    template = "rango/category.html"

    @method_decorator(login_required)
    def get(self, request, id=None):
        if id:
            category = CategoryModel.objects.get(pk=id)
            form = CategoryForm(instance=category)
        else:
            form = CategoryForm()
        return render(request, self.template, {'form': form, 'method': 'get', 'id': id})

    @method_decorator(login_required)
    def post(self, request):
        if request.POST['id']:
            id = request.POST['id']
            category = CategoryModel.objects.get(pk=id)
            form = CategoryForm(instance=category, data=request.POST)
        else:
            id = None
            form = CategoryForm(data=request.POST)

        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('rango:index'))
        else:
            print(form.errors)

        return render(request, self.template, {'form': form, 'method': 'post', 'id': id})


@login_required
def CategoryDelete(request, id):
    category = CategoryModel.objects.get(pk=id)
    category.delete()
    return HttpResponseRedirect('/')


def ListCategories(request):
    category_list = CategoryModel.objects.order_by('-likes')
    context_dict = {'categories': category_list}
    return render(request, 'rango/categories.html', context_dict)


def ShowCategory(request, category_name_slug):
    context_dict = {}
    try:
        category = CategoryModel.objects.get(slug=category_name_slug)
        pages = PageModel.objects.filter(category=category)

        context_dict['category'] = category
        context_dict['pages'] = pages
    except CategoryModel.DoesNotExist:
        pass
    return render(request, 'rango/category-show.html', context_dict)


def GoToCategory(request):
    if request.method == 'GET':
        if 'category_id' in request.GET:
            category_id = request.GET['category_id']
            try:
                category = CategoryModel.objects.get(id=category_id)
                if category:
                    category.views += 1
                    category.save()
                    return HttpResponseRedirect(reverse('rango:category', args=(category.slug,)))
                else:
                    return HttpResponse("Não Existe categoria!")
            except CategoryModel.DoesNotExist:
                return HttpResponse("Categoria não existe")
    return HttpResponseRedirect(reverse('rango:index'))


def LikeCategory(request):
    if request.method == 'GET':
        if 'category_id' in request.GET:
            category_id = request.GET['category_id']
            try:
                category = CategoryModel.objects.get(id=category_id)
                if category:
                    category.likes += 1
                    category.save()
                    return HttpResponseRedirect(reverse('rango:category', args=(category.slug,)))
                else:
                    return HttpResponse("Não Existe categoria!")
            except CategoryModel.DoesNotExist:
                return HttpResponse("Categoria não existe")
    return HttpResponseRedirect(reverse('rango:index'))

rango/views/index.py
# coding: utf-8
from rango.models import CategoryModel, QuestionModel, PageModel
from django.shortcuts import render


def index(request):
    template = "rango/index.html"
    latest_question_list = QuestionModel.objects.order_by('-pub_date')[:5]
    category_list = CategoryModel.objects.order_by('-likes')[:5]
    page_list = PageModel.objects.order_by('-views')[:5]

    context_dict = {'categories': category_list, 'pages': page_list, 'latest_question_list': latest_question_list}

    return render(request, template, context_dict)

rango/views/page.py
# coding: utf-8
from django.shortcuts import redirect
from rango.forms import PageForm
from rango.views.category import *
from rango.models import CategoryModel, PageModel


class PageView(View):
    template = "rango/page.html"

    @method_decorator(login_required)
    def get(self, request, id=None, category_name_slug=None):
        if id:
            page = PageModel.objects.get(pk=id)
            category_name_slug = page.category.slug
            form = PageForm(instance=page)
        else:
            form = PageForm()
        return render(request, self.template, {'form': form, 'method': 'get', 'id': id, 'category': category_name_slug})

    @method_decorator(login_required)
    def post(self, request, category_name_slug=None):
        try:
            cat = CategoryModel.objects.get(slug=category_name_slug)
        except CategoryModel.DoesNotExist:
            cat = None

        if request.POST['id']:  # EDIÇÃO
            id = request.POST['id']
            page = PageModel.objects.get(pk=id)
            form = PageForm(instance=page, data=request.POST)
        else:  # CADASTRO NOVO
            id = None
            form = PageForm(data=request.POST)

        if form.is_valid():
            page = form.save(commit=False)
            page.category = cat
            page.views = 0
            page.save()
            return HttpResponseRedirect('/')
        else:
            print(form.errors)

        return render(request, self.template, {'form': form, 'method': 'post', 'id': id, 'category': category_name_slug})


@login_required
def PageDelete(request, id):
    page = PageModel.objects.get(pk=id)
    page.delete()
    return HttpResponseRedirect('/')


def Pages(request):
    page_list = PageModel.objects.order_by('-views')
    context_dict = {'pages': page_list}

    return render(request, 'rango/pages.html', context_dict)


def GoToPage(request):
    if request.method == 'GET':
        if 'page_id' in request.GET:
            page_id = request.GET['page_id']
            try:
                page = PageModel.objects.get(id=page_id)
                if page:
                    page.views += 1
                    page.save()
                    return redirect(page.url)
                else:
                    return HttpResponse("Não Existe página!")
            except PageModel.DoesNotExist:
                return HttpResponse("Página não existe")
    return HttpResponseRedirect(reverse('rango:index'))

rango/views/question.py
# coding: utf-8
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from rango.models import QuestionModel, ChoiceModel
from django.core.urlresolvers import reverse


def detail(request, question_id):
    question = get_object_or_404(QuestionModel, pk=question_id)
    return render(request, 'rango/detail.html', {'question': question})


def vote(request, question_id):
    question = get_object_or_404(QuestionModel, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, ChoiceModel.DoesNotExist):
        return render(request, 'rango/detail.html', {
            'question': question,
            'error_message': "Deve selecionar uma escolha!",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('rango:results', args=(question.id,)))


def results(request, question_id):
    question = get_object_or_404(QuestionModel, pk=question_id)
    return render(request, 'rango/results.html', {'question': question})

rango/views/search.py
# coding: utf-8
from django.shortcuts import render
from rango.bing_search import run_query


def Search(request):
    result_list = []

    if request.method == 'POST':
        query = request.POST['query'].strip()

        if query:
            result_list = run_query(query)

    return render(request, 'rango/search.html', {'result_list': result_list})

rango/views/user.py
# coding: utf-8
from django.shortcuts import render, HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.contrib.auth import authenticate, login
from rango.forms import UserForm, UserProfileForm


def AddUser(request):
    template = 'rango/add_user.html'

    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return HttpResponseRedirect('/')
        else:
            print form.errors
    else:
        form = UserForm()

    return render(request, template, {'form': form})


@login_required
def UserLogout(request):
    logout(request)
    return HttpResponseRedirect('/rango/')


def Register(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user

            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']
            profile.save()
            registered = True
        else:
            print user_form.errors, profile_form.errors
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    return render(request,
            'rango/register.html',
            {'user_form': user_form, 'profile_form': profile_form, 'registered': registered} )


def UserLogin(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect('/rango/')
            else:
                return HttpResponse("Your Rango account is disabled.")
        else:
            print "Invalid login details: {0}, {1}".format(username, password)
            return HttpResponse("Invalid login details supplied.")
    else:
        return render(request, 'rango/login.html', {})

rango/templates/rango/categories.html
{% extends 'rango/base.html' %}

{% block title %} Categorias {% endblock %}

{% block body_block %}

    <div class="page-header">
        <h1>Lista de categorias</h1>
    </div>

    {% if categories %}
        <div class="list-group col-sm-4">
            {% for category in categories %}
                <a type='button' class='list-group-item'
                   href="{% url 'rango:gotocategory' %}?category_id={{ category.id }}">
                    {{ category.name }}
                </a>
            {% endfor %}
        </div>
    {% else %}
        <strong>Nenhuma categoria.</strong>
    {% endif %}

    {% if user.is_authenticated %}
        <div class="list-group col-sm-12">
            <p><a href="{% url 'rango:cad_category' %}" class='btn btn-info'>Adicionar categoria</a></p>
        </div>
    {% endif %}

{% endblock %}

rango/templates/rango/category-show.html
{% extends 'rango/base.html' %}

{% block title %}
    {% if category %}
        {{ category.name }}
    {% else %}
        Categoria não existe
    {% endif %}
{% endblock %}

{% block body_block %}

    {% if category %}
        <div class="page-header">
            <h1>{{ category.name }}</h1>
            <h5>
                Likes: {{ category.likes }}
                <a href="{% url 'rango:likecategory' %}?category_id={{ category.id }}"><span
                        class='glyphicon glyphicon-thumbs-up rango-icon-like'></span></a>
            </h5>
            <h5>Views: {{ category.views }}</h5>
            <h5>Slug: {{ category.slug }}</h5>
            <h5>ID: {{ category.id }}</h5>

            {% if user.is_authenticated %}
                <a href="{% url 'rango:deleta_category' category.id %}" class="btn btn-danger">Excluir</a>
                <a href="{% url 'rango:edita_category' category.id %}" class="btn btn-primary">Editar</a>
            {% endif %}
        </div>


        {% if pages %}
            <div class="list-group col-sm-6">
                {% for page in pages %}
                    <a type="button" class='list-group-item'
                       href="{% url 'rango:gotopage' %}?page_id={{ page.id }}">
                        {{ page.title }}
                        <span class="badge">{{ page.views }}</span>
                        {% if user.is_authenticated %}
                            <a href="{% url 'rango:deleta_page' page.id %}" class="rango-badge rango-badge-remove">
                                <i class="glyphicon glyphicon-remove"></i></a>
                            <a href="{% url 'rango:edita_page' page.id %}" class="rango-badge rango-badge-edit">
                                <i class="glyphicon glyphicon-pencil"></i></a>
                        {% endif %}
                    </a>
                {% endfor %}
            </div>
        {% else %}
            <p><strong>Sem páginas nesta categoria.</strong></p>
        {% endif %}

        {% if user.is_authenticated %}
            <div class="list-group col-sm-12">
                <a href="{% url 'rango:cad_page' category.slug %}" class='btn btn-success'>Adicionar página</a>
            </div>
        {% endif %}

        <div class='list-group col-sm-12'>
            <hr/>
            <form class="form-inline" id="user_form" method="post" action="{% url 'rango:search' %}">
                {% csrf_token %}
                <input class="form-control" type="text" size="50" name="query" value="" id="query"
                       placeholder="Pesquise por uma página..."/>
                <input class="btn btn-primary" type="submit" name="submit" value="Pesquisar"/>
                <br/>
                <br/>
            </form>
        </div>

    {% else %}
        <p class="bg-danger text-danger rango-warning"><strong>Essa categoria não existe</strong></p>
    {% endif %}

{% endblock %}

rango/templates/rango/category.html
{% extends 'rango/base.html' %}

{% block title %}
    {% if id %}
        Edição de categoria
    {% else %}
        Nova categoria
    {% endif %}
{% endblock %}

{% block body_block %}

    {% if not id %}
        <h2 class="form-signin-heading">Cadastro de Categoria:</h2><br/>
    {% else %}
        <h2 class="form-signin-heading">Edição da Categoria</h2><br/>
    {% endif %}

    <form role="form" id="category_form" method="post" action="{% url 'rango:cad_category' %}">
        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}

        {% if not id %}
            <input type="hidden" name="id" value="">
        {% else %}
            <input type="hidden" name="id" value="{{ id }}">
        {% endif %}

        <div class="form-group" style="width: 250px">
            <label>{{ form.name.help_text }}</label><br/>
            {{ form.name }}
            {% if form.name.errors %}
                <div class="alert alert-danger rango-input-error" role="alert">
                    {{ form.name.errors }}
                </div>
            {% endif %}
        </div>

        {% include 'rango/blocos/buttons_form.html' %}
    </form>

{% endblock %}

rango/templates/rango/cats.html
<ul class="nav nav-sidebar">
	{% if cats %}
	    {% for category in cats %}
		    {% if category == act_cat %}
		    	<li class="active">
    		{% else %}
    			<li>
			{% endif %}
		    <a href="{% url 'rango:gotocategory' %}?category_id={{ category.id }}">{{ category.name }}</a></li>
		{% endfor %}
	{% else %}
    	<p class="bg-danger text-danger rango-warning">Não há categorias ainda.</p>
	{% endif %}
</ul>

rango/templates/rango/detail.html
{% extends 'rango/base.html' %}

{% block title %} Detalhes {% endblock %}

{% block body_block %}

	<div class="page-header">
        <h1>{{ question.question_text }}</h1>
    </div>

	{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

	<form action="{% url 'rango:vote' question.id %}" method="post">
	    {% csrf_token %}
	    {% for choice in question.choice_set.all %}
	        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
	        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
	    {% endfor %}
	    <br/>
	    <input type="submit" value="Vote" class='btn btn-success' />
	</form>

{% endblock %}

rango/templates/rango/index.html
{% extends 'rango/base.html' %}

{% block title %}Index{% endblock %}

{% block body_block %}

    <div class="page-header">
        {% if user.is_authenticated %}
            <h1>Rango diz... Alô {{ user.username }}</h1><br/>
        {% else %}
            <h1>Rango diz... Alô!</h1><br/>
        {% endif %}
    </div>
    
    <div class="row placeholders">
        <div class="col-xs-12 col-sm-4 placeholder">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">5 Categorias mais curtidas</h3>
                </div>
            </div>

            {% if categories %}
                <div class="list-group">
                    {% for category in categories %}
                        <a type='button' class='list-group-item' href="{% url 'rango:gotocategory' %}?category_id={{ category.id }}">
                            {{ category.name }}
                        </a>
                    {% endfor %}
                    <a type='button' class='list-group-item list-group-item-info' href="{% url 'rango:categories' %}">
                        <i class='glyphicon glyphicon-plus'></i> Ver mais
                    </a>
                </div>
            {% else %}
                <strong>Sem categorias.</strong>
            {% endif %}
        </div>

        <div class="col-xs-12 col-sm-4 placeholder">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">5 Páginas mais visualizadas</h3>
                </div>
            </div>

            {% if pages %}
                <div class="list-group">
                    {% for page in pages %}
                        <a type='button' class='list-group-item' href="{% url 'rango:gotopage' %}?page_id={{ page.id }}">
                            {{ page.title }}
                            <span class="badge">{{ page.views }}</span>
                        </a>
                    {% endfor %}
                    <a type='button' class='list-group-item list-group-item-info' href="{% url 'rango:pages' %}">
                        <i class='glyphicon glyphicon-plus'></i> Ver mais
                    </a>
                </div>
            {% else %}
                <strong>Não existem páginas.</strong>
            {% endif %}
        </div>
    </div>


    {% if latest_question_list %}
        <div class="page-header">
            <h4>5 Questões por ordem de data de publicação</h4>
        </div>
        
        <ul>
        {% for question in latest_question_list %}
            <li><a href="{% url 'rango:detail' question.id %}">{{ question.question_text }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p class="bg-danger text-danger rango-warning">Não há enquetes disponíveis.</p>
    {% endif %}

{% endblock %}

rango/templates/rango/login.html
{% extends 'rango/base.html' %}

{% load static %}

{% block title %} Login {% endblock %}

{% block body_block %}

    <link href="{% static 'css/signin.css' %}" rel="stylesheet">

    <form class="form-signin rango-form-login" role="form" method="post" action="{%  url 'rango:login' %}" id="login_form">
        {% csrf_token %}

        <h2 class="form-signin-heading">Entrar</h2><br/>

        <input class="form-control" placeholder="Usuário" id="id_username" maxlength="254" name="username" type="text" required autofocus=""/><br/>
        
        <input type="password" class="form-control" placeholder="Senha" id="id_password" name="password" required /><br/>

        <button class="btn btn-lg btn-primary btn-block" type="submit" value="Submit" >Entrar</button>
    </form>

{% endblock %}

rango/templates/rango/pages.html
{% extends 'rango/base.html' %}

{% block title %} Páginas {% endblock %}

{% block body_block %}

    <div class="page-header">
        <h1>Lista de páginas</h1>
    </div>

    {% if pages %}
        <div class="list-group col-sm-4">
            {% for page in pages %}
                <a type='button' class='list-group-item' href="{% url 'rango:gotopage' %}?page_id={{ page.id }}">
                    {{ page.title }}
                    <span class="badge">{{ page.views }}</span>
                </a>
            {% endfor %}
        </div>
    {% else %}
        <strong>Nenhuma página.</strong>
    {% endif %}

    {% if user.is_authenticated %}
        <div class="list-group col-sm-12">
            <p><a href="{% url 'rango:categories' %}" class='btn btn-info'>Adicionar página</a></p>
        </div>
    {% endif %}

{% endblock %}

rango/templates/rango/register.html
{% extends 'rango/base.html' %}

{% block title %} Registre-se {% endblock %}

{% block body_block %}

    {% if registered %}
        <strong>Obrigado por se registrar!</strong>
        <a href="{% url 'rango:index' %}">Página inicial</a><br/>
    {% else %}
        <div class="page-header">
            <h1>Novo cadastro</h1>
        </div>

        <form id="user_form" method="post" action="{% url 'rango:register' %}" enctype="multipart/form-data">
            {% csrf_token %}

            <div class='col-sm-12'>
                <div class="form-group col-sm-3">

                    <div class="form-group">
                        <p class="required"><label for="id_username">Nome de usuário:</label>
                            <input class="form-control" id="id_username" maxlength="30" name="username" type="text"
                                   placeholder="Digite seu nome de usuário..."
                                   title="Obrigatório. 30 caracteres ou menos. Somente letras, dígitos e @/./+/-/_."/>
                        </p>
                    </div>

                    <div class="form-group">
                        <p class="required"><label for="id_email">E-mail:</label>
                            <input class="form-control" id="id_email" name="email" type="email"
                                   placeholder="Digite seu email..."/>
                        </p>
                    </div>

                    <div class="form-group">
                        <p><label for="id_website">Site:</label>
                            <input class="form-control" id="id_website" name="website" type="url"
                                   placeholder="Digite seu website..."/>
                        </p>
                    </div>

                    <div class="form-group">
                        <p><label for="id_picture">Foto:</label>
                            <input id="id_picture" name="picture" type="file"
                                   placeholder="Faça upload de sua imagem..."/>
                        </p>
                    </div>

                    <div class="form-group">
                        <p class="required"><label for="id_password">Senha:</label>
                            <input class="form-control" id="id_password" name="password" type="password"
                                   placeholder="Digite a nova senha..."/>
                        </p>
                    </div>

                    <br/>
                    <input type="submit" class="btn btn-success center-block" name="submit" value="Cadastrar">

                </div>
            </div>
        </form>
    {% endif %}

{% endblock %}

rango/templates/rango/results.html
{% extends 'rango/base.html' %}

{% block title %} Resultados {% endblock %}

{% block body_block %}

	<div class="page-header">
        <h1>{{ question.question_text }}</h1>
    </div>

	<ul>
	{% for choice in question.choice_set.all %}
	    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
	{% endfor %}
	</ul>
	<br/>
	<a href="{% url 'rango:detail' question.id %}" class='btn btn-success'>Votar novamente?</a>

{% endblock %}